name: Images for training AI with tensorflow and huggingface on OVH

on:
  push:
    branches: 
      - main
    paths:
      - OVH/AI/**

jobs:
  push:
    name: "OVH-AI-${{ matrix.version }}"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        version:
          - python3.10
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./OVH/AI
          file: ./OVH/AI/${{ matrix.version }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/legabi/containers:ai-training-${{ matrix.version }}
      # - name: Login to OVH Docker Registry
      #   run: docker login registry.bhs.ai.cloud.ovh.net -u ${{ secrets.OVH_USERNAME }} -p ${{ secrets.OVH_PASSWORD }}
      # - name: Tag and push image to OVH Docker Registry
      #   run: |
      #     docker pull ghcr.io/legabi/containers:ai-training-${{ matrix.version }}
      #     docker tag ghcr.io/legabi/containers:ai-training-${{ matrix.version }} registry.bhs.ai.cloud.ovh.net/601f2816a04749f3b70a2e31d505054b/ai-training:${{ matrix.version }}
      #     docker push registry.bhs.ai.cloud.ovh.net/601f2816a04749f3b70a2e31d505054b/ai-training:${{ matrix.version }}