name: Images for Pterodactyl NodeJS with debian

on:
  push:
    branches: 
      - main
    paths:
      - Pterodactyl/**

jobs:
  push:
    name: "Pterodactyl-DNJS-${{ matrix.version }}"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        version:
          - nodejs17
          - nodejs18
          - nodejs19
          - nodejs20
          - nodejs21
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./Pterodactyl/Debian-NodeJS
          file: ./Pterodactyl/Debian-NodeJS/${{ matrix.version }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/legabi/containers:pterodactyl-dnjs-${{ matrix.version }}